% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Dec-2021 13:17:58
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
                                                                

Bool = Simulink.AliasType;
Bool.Description = '';
Bool.DataScope = 'Auto';
Bool.HeaderFile = 'Rte_Type.h';
Bool.BaseType = 'boolean';

CntAbsMod = Simulink.AliasType;
CntAbsMod.Description = ['A monotonic absolute counter which resets to ' ...
                         '0 on overflow. Overflow depends upon the impl' ...
                         'ementation type used.'];
CntAbsMod.DataScope = 'Auto';
CntAbsMod.HeaderFile = 'Rte_Type.h';
CntAbsMod.BaseType = 'uint16';

Std_ReturnType = Simulink.AliasType;
Std_ReturnType.Description = '';
Std_ReturnType.DataScope = 'Auto';
Std_ReturnType.HeaderFile = 'Rte_Type.h';
Std_ReturnType.BaseType = 'uint8';

TiInSec = Simulink.AliasType;
TiInSec.Description = '';
TiInSec.DataScope = 'Auto';
TiInSec.HeaderFile = 'Rte_Type.h';
TiInSec.BaseType = 'float32';

float32 = Simulink.NumericType;
float32.Description = '';
float32.DataScope = 'Auto';
float32.HeaderFile = 'Rte_Type.h';
float32.DataTypeMode = 'Single';
float32.SignednessBool = true;
float32.WordLength = 32;
float32.FixedExponent = 0;
float32.SlopeAdjustmentFactor = 1;
float32.Bias = 0;
float32.DataTypeOverride = 'Inherit';
float32.IsAlias = true;

float64 = Simulink.NumericType;
float64.Description = '';
float64.DataScope = 'Auto';
float64.HeaderFile = 'Rte_Type.h';
float64.DataTypeMode = 'Double';
float64.SignednessBool = true;
float64.WordLength = 64;
float64.FixedExponent = 0;
float64.SlopeAdjustmentFactor = 1;
float64.Bias = 0;
float64.DataTypeOverride = 'Inherit';
float64.IsAlias = true;

