% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Dec-2021 13:17:58
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
                                                        

Bool = Simulink.AliasType;
Bool.Description = '';
Bool.DataScope = 'Auto';
Bool.HeaderFile = 'Rte_Type.h';
Bool.BaseType = 'boolean';

CntAbsMod = Simulink.AliasType;
CntAbsMod.Description = ['A monotonic absolute counter which resets to ' ...
                         '0 on overflow. Overflow depends upon the impl' ...
                         'ementation type used.'];
CntAbsMod.DataScope = 'Auto';
CntAbsMod.HeaderFile = 'Rte_Type.h';
CntAbsMod.BaseType = 'uint16';

EolDurnLong = AUTOSAR.Parameter;
EolDurnLong.Value =0.9;
EolDurnLong.CoderInfo.StorageClass = 'Custom';
EolDurnLong.CoderInfo.Alias = '';
EolDurnLong.CoderInfo.Alignment = -1;
EolDurnLong.CoderInfo.CustomStorageClass = 'InternalCalPrm';
EolDurnLong.CoderInfo.CustomAttributes.HeaderFile = '';
EolDurnLong.CoderInfo.CustomAttributes.PerInstanceBehavior = ...
  ['Each instance of the Software Component has its own copy of the par' ...
   'ameter'];
EolDurnLong.Description = '';
EolDurnLong.DataType = 'TiInSec';
EolDurnLong.Min = [];
EolDurnLong.Max = [];
EolDurnLong.DocUnits = '';
EolDurnLong.SwCalibrationAccess = 'ReadWrite';
EolDurnLong.DisplayFormat = '';

EolDurnSho = AUTOSAR.Parameter;
EolDurnSho.Value = 0.6;
EolDurnSho.CoderInfo.StorageClass = 'Custom';
EolDurnSho.CoderInfo.Alias = '';
EolDurnSho.CoderInfo.Alignment = -1;
EolDurnSho.CoderInfo.CustomStorageClass = 'InternalCalPrm';
EolDurnSho.CoderInfo.CustomAttributes.HeaderFile = '';
EolDurnSho.CoderInfo.CustomAttributes.PerInstanceBehavior = ...
  ['Each instance of the Software Component has its own copy of the par' ...
   'ameter'];
EolDurnSho.Description = '';
EolDurnSho.DataType = 'TiInSec';
EolDurnSho.Min = [];
EolDurnSho.Max = [];
EolDurnSho.DocUnits = '';
EolDurnSho.SwCalibrationAccess = 'ReadWrite';
EolDurnSho.DisplayFormat = '';

EolDurnStab = AUTOSAR.Parameter;
EolDurnStab.Value = 0;
EolDurnStab.CoderInfo.StorageClass = 'Custom';
EolDurnStab.CoderInfo.Alias = '';
EolDurnStab.CoderInfo.Alignment = -1;
EolDurnStab.CoderInfo.CustomStorageClass = 'InternalCalPrm';
EolDurnStab.CoderInfo.CustomAttributes.HeaderFile = '';
EolDurnStab.CoderInfo.CustomAttributes.PerInstanceBehavior = ...
  ['Each instance of the Software Component has its own copy of the par' ...
   'ameter'];
EolDurnStab.Description = '';
EolDurnStab.DataType = 'TiInSec';
EolDurnStab.Min = [];
EolDurnStab.Max = [];
EolDurnStab.DocUnits = '';
EolDurnStab.SwCalibrationAccess = 'ReadWrite';
EolDurnStab.DisplayFormat = '';

EveGORMDHARMCPTOSwtPosnInvld_EventStatusInputDS = mpt.Signal;
EveGORMDHARMCPTOSwtPosnInvld_EventStatusInputDS.CoderInfo.StorageClass = ...
  'Auto';
EveGORMDHARMCPTOSwtPosnInvld_EventStatusInputDS.Description = '';
EveGORMDHARMCPTOSwtPosnInvld_EventStatusInputDS.DataType = ...
  'Enum: Dem_EventStatusType';
EveGORMDHARMCPTOSwtPosnInvld_EventStatusInputDS.Min = [];
EveGORMDHARMCPTOSwtPosnInvld_EventStatusInputDS.Max = [];
EveGORMDHARMCPTOSwtPosnInvld_EventStatusInputDS.DocUnits = '';
EveGORMDHARMCPTOSwtPosnInvld_EventStatusInputDS.Dimensions = 1;
EveGORMDHARMCPTOSwtPosnInvld_EventStatusInputDS.DimensionsMode = 'auto';
EveGORMDHARMCPTOSwtPosnInvld_EventStatusInputDS.Complexity = 'real';
EveGORMDHARMCPTOSwtPosnInvld_EventStatusInputDS.SampleTime = -1;
EveGORMDHARMCPTOSwtPosnInvld_EventStatusInputDS.InitialValue = ...
  'Dem_EventStatusType.getDefaultValue';

FaultSetTime = 30;

GORMDHARMCPTOSwtPosnInvld_EventFailedOutputDS = mpt.Signal;
GORMDHARMCPTOSwtPosnInvld_EventFailedOutputDS.CoderInfo.StorageClass = ...
  'Auto';
GORMDHARMCPTOSwtPosnInvld_EventFailedOutputDS.Description = '';
GORMDHARMCPTOSwtPosnInvld_EventFailedOutputDS.DataType = 'boolean';
GORMDHARMCPTOSwtPosnInvld_EventFailedOutputDS.Min = [];
GORMDHARMCPTOSwtPosnInvld_EventFailedOutputDS.Max = [];
GORMDHARMCPTOSwtPosnInvld_EventFailedOutputDS.DocUnits = '';
GORMDHARMCPTOSwtPosnInvld_EventFailedOutputDS.Dimensions = 1;
GORMDHARMCPTOSwtPosnInvld_EventFailedOutputDS.DimensionsMode = 'auto';
GORMDHARMCPTOSwtPosnInvld_EventFailedOutputDS.Complexity = 'real';
GORMDHARMCPTOSwtPosnInvld_EventFailedOutputDS.SampleTime = -1;
GORMDHARMCPTOSwtPosnInvld_EventFailedOutputDS.InitialValue = 'false';

P_Std_ReturnType = Simulink.Parameter;
P_Std_ReturnType.Value = 0;
P_Std_ReturnType.CoderInfo.StorageClass = 'Auto';
P_Std_ReturnType.Description = '';
P_Std_ReturnType.DataType = 'Std_ReturnType';
P_Std_ReturnType.Min = [];
P_Std_ReturnType.Max = [];
P_Std_ReturnType.DocUnits = '';

RecCtrlSelr = Simulink.Bus;
RecCtrlSelr.Description = ['A Selector Control represents mechanisms wh' ...
                           'ich select at most one of a set of possible' ...
                           ' values. The mechanism can be a mutually ex' ...
                           'clusive bank of buttons, a selector dial, o' ...
                           'r some sort of multiple position rocker swi' ...
                           'tch. They can be latching or momentary. The' ...
                           ' possible selections are represented as an ' ...
                           'array of Discrete Controls so the consumer ' ...
                           'can distinguish between Off, On, and Held f' ...
                           'or each selectable value. The Selected valu' ...
                           'e is also provided for convenience with zer' ...
                           'o meaning no value is selected (i.e. the ne' ...
                           'utral state which also implies all listed D' ...
                           'iscrete Controls are Off). The number of Tr' ...
                           'ansitions from any selector being not off t' ...
                           'o all selectors being off is also provided.' ...
                           ''];
RecCtrlSelr.DataScope = 'Auto';
RecCtrlSelr.HeaderFile = 'Rte_Type.h';
RecCtrlSelr.Alignment = -1;
saveVarsTmp{1} = Simulink.BusElement;
saveVarsTmp{1}.Name = 'Seln';
saveVarsTmp{1}.Complexity = 'real';
saveVarsTmp{1}.Dimensions = [1 1];
saveVarsTmp{1}.DataType = 'Enum: EnCtrlSeln';
saveVarsTmp{1}.Min = [];
saveVarsTmp{1}.Max = [];
saveVarsTmp{1}.DimensionsMode = 'Fixed';
saveVarsTmp{1}.SamplingMode = 'Sample based';
saveVarsTmp{1}.SampleTime = -1;
saveVarsTmp{1}.DocUnits = '';
saveVarsTmp{1}.Description = ['The index of the selected Discrete Contr' ...
                              'ol with zero meaning no Discrete Control' ...
                              ' is not Off (i.e. the neutral state).'];
saveVarsTmp{1}(2, 1) = Simulink.BusElement;
saveVarsTmp{1}(2, 1).Name = 'SeldSt';
saveVarsTmp{1}(2, 1).Complexity = 'real';
saveVarsTmp{1}(2, 1).Dimensions = [1 1];
saveVarsTmp{1}(2, 1).DataType = 'Enum: EnCtrlDisSt';
saveVarsTmp{1}(2, 1).Min = [];
saveVarsTmp{1}(2, 1).Max = [];
saveVarsTmp{1}(2, 1).DimensionsMode = 'Fixed';
saveVarsTmp{1}(2, 1).SamplingMode = 'Sample based';
saveVarsTmp{1}(2, 1).SampleTime = -1;
saveVarsTmp{1}(2, 1).DocUnits = '';
saveVarsTmp{1}(2, 1).Description = '';
saveVarsTmp{1}(3, 1) = Simulink.BusElement;
saveVarsTmp{1}(3, 1).Name = 'Trans';
saveVarsTmp{1}(3, 1).Complexity = 'real';
saveVarsTmp{1}(3, 1).Dimensions = [1 1];
saveVarsTmp{1}(3, 1).DataType = 'CntAbsMod';
saveVarsTmp{1}(3, 1).Min = [];
saveVarsTmp{1}(3, 1).Max = [];
saveVarsTmp{1}(3, 1).DimensionsMode = 'Fixed';
saveVarsTmp{1}(3, 1).SamplingMode = 'Sample based';
saveVarsTmp{1}(3, 1).SampleTime = -1;
saveVarsTmp{1}(3, 1).DocUnits = '';
saveVarsTmp{1}(3, 1).Description = ['The count over time of the Transit' ...
                                    'ions from any selectable value bei' ...
                                    'ng not Off to all selectable value' ...
                                    's being Off, or the Selector from ' ...
                                    'not 0 to 0.'];
saveVarsTmp{1}(4, 1) = Simulink.BusElement;
saveVarsTmp{1}(4, 1).Name = 'Sts';
saveVarsTmp{1}(4, 1).Complexity = 'real';
saveVarsTmp{1}(4, 1).Dimensions = [1 1];
saveVarsTmp{1}(4, 1).DataType = 'Enum: EnCtrlSts';
saveVarsTmp{1}(4, 1).Min = [];
saveVarsTmp{1}(4, 1).Max = [];
saveVarsTmp{1}(4, 1).DimensionsMode = 'Fixed';
saveVarsTmp{1}(4, 1).SamplingMode = 'Sample based';
saveVarsTmp{1}(4, 1).SampleTime = -1;
saveVarsTmp{1}(4, 1).DocUnits = '';
saveVarsTmp{1}(4, 1).Description = '';
RecCtrlSelr.Elements = saveVarsTmp{1};
clear saveVarsTmp;

SAMPLE_TIME_0p01_S = Simulink.Parameter;
SAMPLE_TIME_0p01_S.Value = 0.01;
SAMPLE_TIME_0p01_S.CoderInfo.StorageClass = 'Custom';
SAMPLE_TIME_0p01_S.CoderInfo.Alias = '';
SAMPLE_TIME_0p01_S.CoderInfo.Alignment = -1;
SAMPLE_TIME_0p01_S.CoderInfo.CustomStorageClass = 'Define';
SAMPLE_TIME_0p01_S.CoderInfo.CustomAttributes.HeaderFile = '';
SAMPLE_TIME_0p01_S.Description = '';
SAMPLE_TIME_0p01_S.DataType = 'TiInSec';
SAMPLE_TIME_0p01_S.Min = [];
SAMPLE_TIME_0p01_S.Max = [];
SAMPLE_TIME_0p01_S.DocUnits = '';

SAMPLE_TIME_10_MS = Simulink.Parameter;
SAMPLE_TIME_10_MS.Value = 10;
SAMPLE_TIME_10_MS.CoderInfo.StorageClass = 'Custom';
SAMPLE_TIME_10_MS.CoderInfo.Alias = '';
SAMPLE_TIME_10_MS.CoderInfo.Alignment = -1;
SAMPLE_TIME_10_MS.CoderInfo.CustomStorageClass = 'Define';
SAMPLE_TIME_10_MS.CoderInfo.CustomAttributes.HeaderFile = '';
SAMPLE_TIME_10_MS.Description = '';
SAMPLE_TIME_10_MS.DataType = 'single';
SAMPLE_TIME_10_MS.Min = [];
SAMPLE_TIME_10_MS.Max = [];
SAMPLE_TIME_10_MS.DocUnits = '';

SAMPLE_TIME_CONFIGSET_0p01_S = 0.01;

Std_ReturnType = Simulink.AliasType;
Std_ReturnType.Description = '';
Std_ReturnType.DataScope = 'Auto';
Std_ReturnType.HeaderFile = 'Rte_Type.h';
Std_ReturnType.BaseType = 'uint8';

TiInSec = Simulink.AliasType;
TiInSec.Description = '';
TiInSec.DataScope = 'Auto';
TiInSec.HeaderFile = 'Rte_Type.h';
TiInSec.BaseType = 'float64';

float32 = Simulink.NumericType;
float32.Description = '';
float32.DataScope = 'Auto';
float32.HeaderFile = 'Rte_Type.h';
float32.DataTypeMode = 'Single';
float32.SignednessBool = true;
float32.WordLength = 32;
float32.FixedExponent = 0;
float32.SlopeAdjustmentFactor = 1;
float32.Bias = 0;
float32.DataTypeOverride = 'Inherit';
float32.IsAlias = true;

float64 = Simulink.NumericType;
float64.Description = '';
float64.DataScope = 'Auto';
float64.HeaderFile = 'Rte_Type.h';
float64.DataTypeMode = 'Double';
float64.SignednessBool = true;
float64.WordLength = 64;
float64.FixedExponent = 0;
float64.SlopeAdjustmentFactor = 1;
float64.Bias = 0;
float64.DataTypeOverride = 'Inherit';
float64.IsAlias = true;

