% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Dec-2021 13:17:58
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
                                                            

JD_ConfigsetAUTOSARMulti10msec = Simulink.ConfigSet;
JD_ConfigsetAUTOSARMulti10msec.set_param('Name', ['JD_ConfigsetAUTOSARM' ...
   'ulti10msec']);
JD_ConfigsetAUTOSARMulti10msec.set_param('Description', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('SystemTargetFile', ['autosar.' ...
   'tlc']);
JD_ConfigsetAUTOSARMulti10msec.set_param('HardwareBoard', 'None');
JD_ConfigsetAUTOSARMulti10msec.set_param('Solver', 'FixedStepDiscrete');
JD_ConfigsetAUTOSARMulti10msec.set_param('StartTime', '0.0');
JD_ConfigsetAUTOSARMulti10msec.set_param('StopTime', 'inf');
JD_ConfigsetAUTOSARMulti10msec.set_param('ConcurrentTasks', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('SampleTimeConstraint', ['Unco' ...
   'nstrained']);
JD_ConfigsetAUTOSARMulti10msec.set_param('SolverType', 'Fixed-step');
JD_ConfigsetAUTOSARMulti10msec.set_param('FixedStep', ['SAMPLE_TIME_CON' ...
   'FIGSET_0p01_S']);
JD_ConfigsetAUTOSARMulti10msec.set_param('EnableMultiTasking', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param(['DecoupledContinuousIntegrati' ...
   'on'], 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('AutoInsertRateTranBlk', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('PositivePriorityOrder', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('LoadExternalInput', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('LoadInitialState', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('SaveTime', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('SaveState', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('SaveFormat', 'Dataset');
JD_ConfigsetAUTOSARMulti10msec.set_param('SaveOutput', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('SaveFinalState', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('SignalLogging', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('SignalLoggingName', 'logsout');
JD_ConfigsetAUTOSARMulti10msec.set_param('DSMLogging', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('DSMLoggingName', 'dsmout');
JD_ConfigsetAUTOSARMulti10msec.set_param('LoggingToFile', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('DatasetSignalFormat', ['times' ...
   'eries']);
JD_ConfigsetAUTOSARMulti10msec.set_param('ReturnWorkspaceOutputs', ['of' ...
   'f']);
JD_ConfigsetAUTOSARMulti10msec.set_param('InspectSignalLogs', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('LimitDataPoints', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('Decimation', '1');
JD_ConfigsetAUTOSARMulti10msec.set_param('BlockReduction', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('ConditionallyExecuteInputs', ...
   'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('BooleanDataType', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('LifeSpan', 'inf');
JD_ConfigsetAUTOSARMulti10msec.set_param(['UseDivisionForNetSlopeComput' ...
   'ation'], 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('UseFloatMulNetSlope', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param(['DefaultUnderspecifiedDataTyp' ...
   'e'], 'double');
JD_ConfigsetAUTOSARMulti10msec.set_param('UseSpecifiedMinMax', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('ZeroExternalMemoryAtStartup', ...
   'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('InitFltsAndDblsToZero', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('ZeroInternalMemoryAtStartup', ...
   'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('EfficientFloat2IntCast', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('EfficientMapNaN2IntZero', ['o' ...
   'n']);
JD_ConfigsetAUTOSARMulti10msec.set_param('NoFixptDivByZeroProtection', ...
   'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimCompilerOptimization', ['o' ...
   'ff']);
JD_ConfigsetAUTOSARMulti10msec.set_param('AccelVerboseBuild', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('DefaultParameterBehavior', ['I' ...
   'nlined']);
JD_ConfigsetAUTOSARMulti10msec.set_param('OptimizeBlockIOStorage', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('LocalBlockOutputs', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('ExpressionFolding', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('BufferReuse', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('GlobalBufferReuse', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('GlobalVariableUsage', 'None');
JD_ConfigsetAUTOSARMulti10msec.set_param('OptimizeBlockOrder', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('OptimizeDataStoreBuffers', ['o' ...
   'n']);
JD_ConfigsetAUTOSARMulti10msec.set_param('BusAssignmentInplaceUpdate', ...
   'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('DifferentSizesBufferReuse', ['o' ...
   'ff']);
JD_ConfigsetAUTOSARMulti10msec.set_param('StrengthReduction', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('EnableMemcpy', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('MemcpyThreshold', 64);
JD_ConfigsetAUTOSARMulti10msec.set_param('BooleansAsBitfields', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('InlineInvariantSignals', ['of' ...
   'f']);
JD_ConfigsetAUTOSARMulti10msec.set_param('RollThreshold', 5);
JD_ConfigsetAUTOSARMulti10msec.set_param('MaxStackSize', ['Inherit from' ...
   ' target']);
JD_ConfigsetAUTOSARMulti10msec.set_param('PassReuseOutputArgsAs', ['Str' ...
   'ucture reference']);
JD_ConfigsetAUTOSARMulti10msec.set_param('StateBitsets', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('DataBitsets', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param(['ActiveStateOutputEnumStorage' ...
   'Type'], 'Native Integer');
JD_ConfigsetAUTOSARMulti10msec.set_param('AdvancedOptControl', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('BufferReusableBoundary', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('AlgebraicLoopMsg', 'error');
JD_ConfigsetAUTOSARMulti10msec.set_param('ArtificialAlgebraicLoopMsg', ...
   'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param('BlockPriorityViolationMsg', ['e' ...
   'rror']);
JD_ConfigsetAUTOSARMulti10msec.set_param('MinStepSizeMsg', 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param('TimeAdjustmentMsg', 'none');
JD_ConfigsetAUTOSARMulti10msec.set_param('MaxConsecutiveZCsMsg', ['erro' ...
   'r']);
JD_ConfigsetAUTOSARMulti10msec.set_param('UnknownTsInhSupMsg', 'error');
JD_ConfigsetAUTOSARMulti10msec.set_param('ConsistencyChecking', 'none');
JD_ConfigsetAUTOSARMulti10msec.set_param('SolverPrmCheckMsg', 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param(['ModelReferenceExtraNoncontSi' ...
   'gs'], 'error');
JD_ConfigsetAUTOSARMulti10msec.set_param('StateNameClashWarn', ['warnin' ...
   'g']);
JD_ConfigsetAUTOSARMulti10msec.set_param(['SimStateInterfaceChecksumMis' ...
   'matchMsg'], 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimStateOlderReleaseMsg', ['e' ...
   'rror']);
JD_ConfigsetAUTOSARMulti10msec.set_param('InheritedTsInSrcMsg', 'none');
JD_ConfigsetAUTOSARMulti10msec.set_param('MultiTaskRateTransMsg', ['err' ...
   'or']);
JD_ConfigsetAUTOSARMulti10msec.set_param('SingleTaskRateTransMsg', ['no' ...
   'ne']);
JD_ConfigsetAUTOSARMulti10msec.set_param('MultiTaskCondExecSysMsg', ['e' ...
   'rror']);
JD_ConfigsetAUTOSARMulti10msec.set_param('TasksWithSamePriorityMsg', ['w' ...
   'arning']);
JD_ConfigsetAUTOSARMulti10msec.set_param('SigSpecEnsureSampleTimeMsg', ...
   'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param('SignalResolutionControl', ['U' ...
   'seLocalSettings']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CheckMatrixSingularityMsg', ['e' ...
   'rror']);
JD_ConfigsetAUTOSARMulti10msec.set_param('IntegerSaturationMsg', ['erro' ...
   'r']);
JD_ConfigsetAUTOSARMulti10msec.set_param('UnderSpecifiedDataTypeMsg', ['n' ...
   'one']);
JD_ConfigsetAUTOSARMulti10msec.set_param('SignalRangeChecking', ['warni' ...
   'ng']);
JD_ConfigsetAUTOSARMulti10msec.set_param('IntegerOverflowMsg', 'error');
JD_ConfigsetAUTOSARMulti10msec.set_param('SignalInfNanChecking', ['erro' ...
   'r']);
JD_ConfigsetAUTOSARMulti10msec.set_param('RTPrefix', 'error');
JD_ConfigsetAUTOSARMulti10msec.set_param('ParameterDowncastMsg', ['erro' ...
   'r']);
JD_ConfigsetAUTOSARMulti10msec.set_param('ParameterOverflowMsg', ['erro' ...
   'r']);
JD_ConfigsetAUTOSARMulti10msec.set_param('ParameterUnderflowMsg', ['err' ...
   'or']);
JD_ConfigsetAUTOSARMulti10msec.set_param('ParameterPrecisionLossMsg', ['w' ...
   'arning']);
JD_ConfigsetAUTOSARMulti10msec.set_param('ParameterTunabilityLossMsg', ...
   'error');
JD_ConfigsetAUTOSARMulti10msec.set_param('ReadBeforeWriteMsg', ['UseLoc' ...
   'alSettings']);
JD_ConfigsetAUTOSARMulti10msec.set_param('WriteAfterReadMsg', ['UseLoca' ...
   'lSettings']);
JD_ConfigsetAUTOSARMulti10msec.set_param('WriteAfterWriteMsg', ['UseLoc' ...
   'alSettings']);
JD_ConfigsetAUTOSARMulti10msec.set_param('MultiTaskDSMMsg', 'error');
JD_ConfigsetAUTOSARMulti10msec.set_param('UniqueDataStoreMsg', 'error');
JD_ConfigsetAUTOSARMulti10msec.set_param(['UnderspecifiedInitialization' ...
   'Detection'], 'Simplified');
JD_ConfigsetAUTOSARMulti10msec.set_param('ArrayBoundsChecking', 'none');
JD_ConfigsetAUTOSARMulti10msec.set_param('AssertControl', 'DisableAll');
JD_ConfigsetAUTOSARMulti10msec.set_param('AllowSymbolicDim', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('UnnecessaryDatatypeConvMsg', ...
   'none');
JD_ConfigsetAUTOSARMulti10msec.set_param('VectorMatrixConversionMsg', ['w' ...
   'arning']);
JD_ConfigsetAUTOSARMulti10msec.set_param('Int32ToFloatConvMsg', ['warni' ...
   'ng']);
JD_ConfigsetAUTOSARMulti10msec.set_param('FixptConstUnderflowMsg', ['wa' ...
   'rning']);
JD_ConfigsetAUTOSARMulti10msec.set_param('FixptConstOverflowMsg', ['err' ...
   'or']);
JD_ConfigsetAUTOSARMulti10msec.set_param('FixptConstPrecisionLossMsg', ...
   'none');
JD_ConfigsetAUTOSARMulti10msec.set_param('SignalLabelMismatchMsg', ['wa' ...
   'rning']);
JD_ConfigsetAUTOSARMulti10msec.set_param('UnconnectedInputMsg', 'error');
JD_ConfigsetAUTOSARMulti10msec.set_param('UnconnectedOutputMsg', ['erro' ...
   'r']);
JD_ConfigsetAUTOSARMulti10msec.set_param('UnconnectedLineMsg', 'error');
JD_ConfigsetAUTOSARMulti10msec.set_param('RootOutportRequireBusObject', ...
   'error');
JD_ConfigsetAUTOSARMulti10msec.set_param('BusObjectLabelMismatch', ['er' ...
   'ror']);
JD_ConfigsetAUTOSARMulti10msec.set_param('StrictBusMsg', ['ErrorOnBusTr' ...
   'eatedAsVector']);
JD_ConfigsetAUTOSARMulti10msec.set_param('NonBusSignalsTreatedAsBus', ['w' ...
   'arning']);
JD_ConfigsetAUTOSARMulti10msec.set_param('BusNameAdapt', ['WarnAndRepai' ...
   'r']);
JD_ConfigsetAUTOSARMulti10msec.set_param('InvalidFcnCallConnMsg', ['err' ...
   'or']);
JD_ConfigsetAUTOSARMulti10msec.set_param('FcnCallInpInsideContextMsg', ...
   'error');
JD_ConfigsetAUTOSARMulti10msec.set_param('SFcnCompatibilityMsg', ['warn' ...
   'ing']);
JD_ConfigsetAUTOSARMulti10msec.set_param(['FrameProcessingCompatibility' ...
   'Msg'], 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param(['ModelReferenceVersionMismatc' ...
   'hMessage'], 'none');
JD_ConfigsetAUTOSARMulti10msec.set_param(['ModelReferenceIOMismatchMess' ...
   'age'], 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param('ModelReferenceIOMsg', 'none');
JD_ConfigsetAUTOSARMulti10msec.set_param(['ModelReferenceDataLoggingMes' ...
   'sage'], 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param('SaveWithDisabledLinksMsg', ['e' ...
   'rror']);
JD_ConfigsetAUTOSARMulti10msec.set_param(['SaveWithParameterizedLinksMs' ...
   'g'], 'error');
JD_ConfigsetAUTOSARMulti10msec.set_param('SFUnusedDataAndEventsDiag', ['w' ...
   'arning']);
JD_ConfigsetAUTOSARMulti10msec.set_param('SFUnexpectedBacktrackingDiag', ...
   'error');
JD_ConfigsetAUTOSARMulti10msec.set_param(['SFInvalidInputDataAccessInCh' ...
   'artInitDiag'], 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param(['SFNoUnconditionalDefaultTran' ...
   'sitionDiag'], 'error');
JD_ConfigsetAUTOSARMulti10msec.set_param(['SFTransitionOutsideNaturalPa' ...
   'rentDiag'], 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param(['SFUnreachableExecutionPathDi' ...
   'ag'], 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param(['SFUndirectedBroadcastEventsD' ...
   'iag'], 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param(['SFTransitionActionBeforeCond' ...
   'itionDiag'], 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param(['SFOutputUsedAsStateInMooreCh' ...
   'artDiag'], 'error');
JD_ConfigsetAUTOSARMulti10msec.set_param(['SFTemporalDelaySmallerThanSa' ...
   'mpleTimeDiag'], 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param('SFSelfTransitionDiag', ['warn' ...
   'ing']);
JD_ConfigsetAUTOSARMulti10msec.set_param(['SFExecutionAtInitializationD' ...
   'iag'], 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param('SFMachineParentedDataDiag', ['w' ...
   'arning']);
JD_ConfigsetAUTOSARMulti10msec.set_param('IgnoredZcDiagnostic', ['warni' ...
   'ng']);
JD_ConfigsetAUTOSARMulti10msec.set_param('InitInArrayFormatMsg', ['warn' ...
   'ing']);
JD_ConfigsetAUTOSARMulti10msec.set_param('MaskedZcDiagnostic', ['warnin' ...
   'g']);
JD_ConfigsetAUTOSARMulti10msec.set_param(['ModelReferenceSymbolNameMess' ...
   'age'], 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param('AllowedUnitSystems', 'all');
JD_ConfigsetAUTOSARMulti10msec.set_param('UnitsInconsistencyMsg', ['war' ...
   'ning']);
JD_ConfigsetAUTOSARMulti10msec.set_param(['AllowAutomaticUnitConversion' ...
   's'], 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('RCSCObservableMsg', 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param('RCSCRenamedMsg', 'warning');
JD_ConfigsetAUTOSARMulti10msec.set_param(['ForceCombineOutputUpdateInSi' ...
   'm'], 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('ProdHWDeviceType', ['Freescal' ...
   'e->32-bit PowerPC']);
JD_ConfigsetAUTOSARMulti10msec.set_param('ProdLongLongMode', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('ProdEqTarget', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('TargetPreprocMaxBitsSint', 32);
JD_ConfigsetAUTOSARMulti10msec.set_param('TargetPreprocMaxBitsUint', 32);
JD_ConfigsetAUTOSARMulti10msec.set_param('UpdateModelReferenceTargets', ...
   'IfOutOfDateOrStructuralChange');
JD_ConfigsetAUTOSARMulti10msec.set_param(['EnableParallelModelReference' ...
   'Builds'], 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param(['ModelReferenceNumInstancesAl' ...
   'lowed'], 'Multi');
JD_ConfigsetAUTOSARMulti10msec.set_param('PropagateVarSize', ['Infer fr' ...
   'om blocks in model']);
JD_ConfigsetAUTOSARMulti10msec.set_param(['ModelReferenceMinAlgLoopOccu' ...
   'rrences'], 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param(['EnableRefExpFcnMdlScheduling' ...
   'Checks'], 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param(['PropagateSignalLabelsOutOfMo' ...
   'del'], 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param(['ModelReferencePassRootInputs' ...
   'ByReference'], 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('ModelDependencies', '');
JD_ConfigsetAUTOSARMulti10msec.set_param(['ParallelModelReferenceErrorO' ...
   'nInvalidPool'], 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param(['SupportModelReferenceSimTarg' ...
   'etCustomCode'], 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('MATLABDynamicMemAlloc', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CompileTimeRecursionLimit', 50);
JD_ConfigsetAUTOSARMulti10msec.set_param('EnableRuntimeRecursion', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('SFSimEcho', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimCtrlC', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimIntegrity', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimGenImportedTypeDefs', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimBuildMode', ['sf_increment' ...
   'al_build']);
JD_ConfigsetAUTOSARMulti10msec.set_param('SimReservedNameArray', []);
JD_ConfigsetAUTOSARMulti10msec.set_param('SimParseCustomCode', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimCustomSourceCode', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimCustomHeaderCode', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimCustomInitializer', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimCustomTerminator', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimUserIncludeDirs', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimUserSources', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimUserLibraries', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimUserDefines', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('SFSimEnableDebug', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('RemoveResetFunc', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('ExistingSharedCode', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('TargetLang', 'C');
JD_ConfigsetAUTOSARMulti10msec.set_param('Toolchain', ['Automatically l' ...
   'ocate an installed toolchain']);
JD_ConfigsetAUTOSARMulti10msec.set_param('BuildConfiguration', ['Faster' ...
   ' Builds']);
saveVarsTmp{1} = cell(1, 2);
saveVarsTmp{1}{1} = 'Execution efficiency';
saveVarsTmp{1}{2} = 'RAM efficiency';
JD_ConfigsetAUTOSARMulti10msec.set_param('ObjectivePriorities', saveVarsTmp{1});
JD_ConfigsetAUTOSARMulti10msec.set_param('CheckMdlBeforeBuild', 'Off');
JD_ConfigsetAUTOSARMulti10msec.set_param('SILDebugging', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('GenCodeOnly', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param(['PackageGeneratedCodeAndArtif' ...
   'acts'], 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('RTWVerbose', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('RetainRTWFile', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('ProfileTLC', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('TLCDebug', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('TLCCoverage', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('TLCAssert', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('RTWUseSimCustomCode', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomSourceCode', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomHeaderCode', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomInclude', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomSource', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomLibrary', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomLAPACKCallback', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomFFTCallback', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomDefine', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomInitializer', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomTerminator', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('CodeExecutionProfiling', ['of' ...
   'f']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CodeProfilingInstrumentation', ...
   'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CreateSILPILBlock', 'None');
JD_ConfigsetAUTOSARMulti10msec.set_param('PortableWordSizes', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('PostCodeGenCommand', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('SaveLog', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('TLCOptions', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('GenerateReport', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('LaunchReport', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('IncludeHyperlinkInReport', ['o' ...
   'n']);
JD_ConfigsetAUTOSARMulti10msec.set_param('GenerateTraceInfo', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('GenerateWebview', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('GenerateTraceReport', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('GenerateTraceReportSl', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('GenerateTraceReportSf', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('GenerateTraceReportEml', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('GenerateCodeMetricsReport', ['o' ...
   'ff']);
JD_ConfigsetAUTOSARMulti10msec.set_param(['GenerateCodeReplacementRepor' ...
   't'], 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('GenerateComments', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimulinkBlockComments', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('StateflowObjectComments', ['o' ...
   'n']);
JD_ConfigsetAUTOSARMulti10msec.set_param('MATLABSourceComments', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('ShowEliminatedStatement', ['o' ...
   'ff']);
JD_ConfigsetAUTOSARMulti10msec.set_param('ForceParamTrailComments', ['o' ...
   'ff']);
JD_ConfigsetAUTOSARMulti10msec.set_param('OperatorAnnotations', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('InsertBlockDesc', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('SFDataObjDesc', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('SimulinkDataObjDesc', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('ReqsInCode', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('EnableCustomComments', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('MATLABFcnDesc', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomSymbolStrGlobalVar', ['$' ...
   'R$N$M']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomSymbolStrType', ['$N$R$' ...
   'M_T']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomSymbolStrField', '$N$M');
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomSymbolStrFcn', ['$R$N$M' ...
   '$F']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomSymbolStrFcnArg', ['rt$' ...
   'I$N$M']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomSymbolStrTmpVar', ['$N$' ...
   'M']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomSymbolStrBlkIO', ['rtb_' ...
   '$N$M']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomSymbolStrMacro', ['$R$N' ...
   '$M']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomSymbolStrUtil', '$N$C');
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomSymbolStrEmxType', ['em' ...
   'xArray_$M$N']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomSymbolStrEmxFcn', ['emx' ...
   '$M$N']);
JD_ConfigsetAUTOSARMulti10msec.set_param('MangleLength', 1);
JD_ConfigsetAUTOSARMulti10msec.set_param('SharedChecksumLength', 8);
JD_ConfigsetAUTOSARMulti10msec.set_param('MaxIdLength', 63);
JD_ConfigsetAUTOSARMulti10msec.set_param('InternalIdentifier', ['Shorte' ...
   'ned']);
JD_ConfigsetAUTOSARMulti10msec.set_param('InlinedPrmAccess', 'Literals');
JD_ConfigsetAUTOSARMulti10msec.set_param('SignalNamingRule', 'None');
JD_ConfigsetAUTOSARMulti10msec.set_param('ParamNamingRule', 'None');
JD_ConfigsetAUTOSARMulti10msec.set_param('DefineNamingRule', 'None');
JD_ConfigsetAUTOSARMulti10msec.set_param('UseSimReservedNames', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('ReservedNameArray', []);
JD_ConfigsetAUTOSARMulti10msec.set_param('IgnoreCustomStorageClasses', ...
   'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('IgnoreTestpoints', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CommentStyle', 'Auto');
JD_ConfigsetAUTOSARMulti10msec.set_param('InsertPolySpaceComments', ['o' ...
   'ff']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CustomUserTokenString', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('TargetLangStandard', ['C99 (I' ...
   'SO)']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CodeReplacementLibrary', ['JD' ...
   ' IFL IFX CRL Tables']);
JD_ConfigsetAUTOSARMulti10msec.set_param('UtilityFuncGeneration', ['Aut' ...
   'o']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CodeInterfacePackaging', ['Re' ...
   'usable function']);
JD_ConfigsetAUTOSARMulti10msec.set_param('GRTInterface', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('PurelyIntegerCode', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('SupportNonFinite', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('SupportComplex', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('SupportAbsoluteTime', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('SupportContinuousTime', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('SupportNonInlinedSFcns', ['of' ...
   'f']);
JD_ConfigsetAUTOSARMulti10msec.set_param('SupportVariableSizeSignals', ...
   'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('MultiwordTypeDef', ['System d' ...
   'efined']);
JD_ConfigsetAUTOSARMulti10msec.set_param('GenerateAllocFcn', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CombineOutputUpdateFcns', ['o' ...
   'n']);
JD_ConfigsetAUTOSARMulti10msec.set_param('IncludeMdlTerminateFcn', ['of' ...
   'f']);
JD_ConfigsetAUTOSARMulti10msec.set_param('MatFileLogging', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('SuppressErrorStatus', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('CombineSignalStateStructs', ['o' ...
   'ff']);
JD_ConfigsetAUTOSARMulti10msec.set_param('ParenthesesLevel', 'Maximum');
JD_ConfigsetAUTOSARMulti10msec.set_param('CastingMode', 'Nominal');
JD_ConfigsetAUTOSARMulti10msec.set_param('GenerateSampleERTMain', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('IncludeFileDelimiter', 'Auto');
JD_ConfigsetAUTOSARMulti10msec.set_param('ERTCustomFileBanners', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('GenerateFullHeader', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('InferredTypesCompatibility', ...
   'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('TargetLibSuffix', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('TargetPreCompLibLocation', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('RemoveDisableFunc', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param(['LUTObjectStructOrderExplicit' ...
   'Values'], 'Size,Breakpoints,Table');
JD_ConfigsetAUTOSARMulti10msec.set_param(['LUTObjectStructOrderEvenSpac' ...
   'ing'], 'Size,Table,Breakpoints');
JD_ConfigsetAUTOSARMulti10msec.set_param('MemSecPackage', ['--- None --' ...
   '-']);
JD_ConfigsetAUTOSARMulti10msec.set_param('MemSecFuncSharedUtil', ['Defa' ...
   'ult']);
JD_ConfigsetAUTOSARMulti10msec.set_param('MemSecFuncInitTerm', ['Defaul' ...
   't']);
JD_ConfigsetAUTOSARMulti10msec.set_param('MemSecFuncExecute', 'Default');
JD_ConfigsetAUTOSARMulti10msec.set_param('MemSecDataParameters', ['Defa' ...
   'ult']);
JD_ConfigsetAUTOSARMulti10msec.set_param('MemSecDataInternal', ['Defaul' ...
   't']);
JD_ConfigsetAUTOSARMulti10msec.set_param('MemSecDataIO', 'Default');
JD_ConfigsetAUTOSARMulti10msec.set_param('MemSecDataConstants', ['Defau' ...
   'lt']);
JD_ConfigsetAUTOSARMulti10msec.set_param('GlobalDataDefinition', 'Auto');
JD_ConfigsetAUTOSARMulti10msec.set_param('GlobalDataReference', 'Auto');
JD_ConfigsetAUTOSARMulti10msec.set_param('ExtMode', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('ERTFilePackagingFormat', ['Mo' ...
   'dular']);
JD_ConfigsetAUTOSARMulti10msec.set_param('EnableUserReplacementTypes', ...
   'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('ConvertIfToSwitch', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('ERTCustomFileTemplate', ['exa' ...
   'mple_file_process.tlc']);
JD_ConfigsetAUTOSARMulti10msec.set_param('ERTDataHdrFileTemplate', ['JD' ...
   '_AUTOSAR_ert_code_template.cgt']);
JD_ConfigsetAUTOSARMulti10msec.set_param('ERTDataSrcFileTemplate', ['JD' ...
   '_AUTOSAR_ert_code_template.cgt']);
JD_ConfigsetAUTOSARMulti10msec.set_param('ERTHdrFileBannerTemplate', ['J' ...
   'D_AUTOSAR_ert_code_template.cgt']);
JD_ConfigsetAUTOSARMulti10msec.set_param('ERTSrcFileBannerTemplate', ['J' ...
   'D_AUTOSAR_ert_code_template.cgt']);
JD_ConfigsetAUTOSARMulti10msec.set_param('EnableDataOwnership', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('GenerateASAP2', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('IndentSize', '2');
JD_ConfigsetAUTOSARMulti10msec.set_param('IndentStyle', 'K&R');
JD_ConfigsetAUTOSARMulti10msec.set_param('InlinedParameterPlacement', ['N' ...
   'onHierarchical']);
JD_ConfigsetAUTOSARMulti10msec.set_param('MultiInstanceErrorCode', ['Er' ...
   'ror']);
JD_ConfigsetAUTOSARMulti10msec.set_param('ParamTuneLevel', 10);
JD_ConfigsetAUTOSARMulti10msec.set_param('EnableSignedLeftShifts', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('EnableSignedRightShifts', ['o' ...
   'n']);
JD_ConfigsetAUTOSARMulti10msec.set_param('PreserveExpressionOrder', ['o' ...
   'ff']);
JD_ConfigsetAUTOSARMulti10msec.set_param('PreserveExternInFcnDecls', ['o' ...
   'n']);
JD_ConfigsetAUTOSARMulti10msec.set_param('PreserveIfCondition', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('RTWCAPIParams', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('RTWCAPIRootIO', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('RTWCAPISignals', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('RTWCAPIStates', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('SignalDisplayLevel', 10);
JD_ConfigsetAUTOSARMulti10msec.set_param(['SuppressUnreachableDefaultCa' ...
   'ses'], 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('BooleanTrueId', 'true');
JD_ConfigsetAUTOSARMulti10msec.set_param('BooleanFalseId', 'false');
JD_ConfigsetAUTOSARMulti10msec.set_param('MaxIdInt32', 'MAX_int32_T');
JD_ConfigsetAUTOSARMulti10msec.set_param('MinIdInt32', 'MIN_int32_T');
JD_ConfigsetAUTOSARMulti10msec.set_param('MaxIdUint32', 'MAX_uint32_T');
JD_ConfigsetAUTOSARMulti10msec.set_param('MaxIdInt16', 'MAX_int16_T');
JD_ConfigsetAUTOSARMulti10msec.set_param('MinIdInt16', 'MIN_int16_T');
JD_ConfigsetAUTOSARMulti10msec.set_param('MaxIdUint16', 'MAX_uint16_T');
JD_ConfigsetAUTOSARMulti10msec.set_param('MaxIdInt8', 'MAX_int8_T');
JD_ConfigsetAUTOSARMulti10msec.set_param('MinIdInt8', 'MIN_int8_T');
JD_ConfigsetAUTOSARMulti10msec.set_param('MaxIdUint8', 'MAX_uint8_T');
JD_ConfigsetAUTOSARMulti10msec.set_param(['TypeLimitIdReplacementHeader' ...
   'File'], '');
JD_ConfigsetAUTOSARMulti10msec.set_param('AutosarCompilerAbstraction', ...
   'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('AutosarMatrixIOAsArray', ['of' ...
   'f']);
JD_ConfigsetAUTOSARMulti10msec.set_param('AutosarMaxShortNameLength', 128);
JD_ConfigsetAUTOSARMulti10msec.set_param('AutosarSchemaVersion', '4.2');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovModelRefEnable', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('RecordCoverage', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovScope', 'EntireSystem');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovEnable', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovExternalEMLEnable', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovSFcnEnable', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovHighlightResults', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovUnsupportedBlockWarning', ...
   'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovLogicBlockShortCircuit', ['o' ...
   'ff']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CovMetricRelationalBoundary', ...
   'off');
JD_ConfigsetAUTOSARMulti10msec.set_param(['CovMetricSaturateOnIntegerOv' ...
   'erflow'], 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovMetricObjectiveConstraint', ...
   'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovMetricSignalSize', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovMetricSignalRange', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovMetricLookupTable', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovMetricStructuralLevel', ['M' ...
   'CDC']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CovMetricSettings', 'dcmw');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovEnableCumulative', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param(['CovSaveCumulativeToWorkspace' ...
   'Var'], 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovCumulativeVarName', ['covC' ...
   'umulativeData']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CovSaveSingleToWorkspaceVar', ...
   'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovSaveName', 'cvdata');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovNameIncrementing', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovReportOnPause', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovHtmlReporting', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovHTMLOptions', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovCumulativeReport', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovCompData', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovForceBlockReductionOff', ['o' ...
   'n']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CovUseTimeInterval', 'off');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovFilter', '');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovShowResultsExplorer', ['of' ...
   'f']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CovOutputDir', ['slcov_output' ...
   '/$ModelName$']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CovSaveOutputData', 'on');
JD_ConfigsetAUTOSARMulti10msec.set_param('CovDataFileName', ['$ModelNam' ...
   'e$_cvdata']);
JD_ConfigsetAUTOSARMulti10msec.set_param('CovMcdcMode', 'Masking');
clear saveVarsTmp;

