function [prjFolders,toolRootFolder] = define_project_path(prjRoot)
    %   Add external folders for the project using the pattern below
    %   NOTE: This is no longer needed with use of Project Folders and Project Reference
    %   **** Be sure that the last line remains only the close bracket ***
    prjFolders={...
%         fullfile(prjRoot,'MBSD','Control_Algorithm'),...
%         fullfile(prjRoot,'MBSD','work'),...
%         fullfile(prjRoot,'MBSD','SignalLayer'),...
%         fullfile(prjRoot,'MBSD','Simulation'),...
%         fullfile(prjRoot,'MBSD','Utilities'),...
        };
    
    %   Modify the tool root folder below as needed
    toolRootFolder = fullfile(fileparts(fileparts(prjRoot)),'GTEEToolLib\EnterpriseTools');
end
